language: python
sudo: false
python:
    - "2.7"

install:
    - pip install .
    - pip install flake8
    - pip install coverage
    - pip install coveralls

script:
    - flake8 half_json tests --max-line-length=200
    - nosetests --cover-package=half_json --with-coverage
    - python setup.py install
    - jsonfixer checks/online.json checks/online.fix.json
    - cd checks && ./runtest.sh

after_success:
  - coveralls
